version: "3"

services:
  db_mamboo:
    container_name: db_cash
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
     - .env
  api_mamboo:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - "db_mamboo"
    env_file:
     - .env